development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: multidb_development
  pool: 5
  username: root
  password:
  host: localhost
  
legacy:
  adapter: postgresql
  encoding: unicode
  database: pgblog_development
  pool: 5
  username: pgblog_user
  password: